In [6]:
import numpy as np

A = np.array([[2, 4],
              [6, 8]])

B = np.array([[1, 3],
              [5, 7]])

print(np.matmul(A,B))

[[ 3  7]
 [11 15]]
[[22 34]
 [46 74]]


In [12]:
A = np.array([[2, 4],
              [6, 8]])

B = np.array([[1, 3],
              [5, 7]])

print(A+B)
print(A*B)
print(A/B)
print(A.T) 
print(np.linalg.inv(A))

[[ 3  7]
 [11 15]]
[[ 2 12]
 [30 56]]
[[2.         1.33333333]
 [1.2        1.14285714]]
[[2 6]
 [4 8]]
[[-1.    0.5 ]
 [ 0.75 -0.25]]


In [14]:
import numpy as np

# Matrix A
A = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

# Matrix B
B = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix B:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [23]:
print(A.shape)
print(B.shape)
print(A.size)
print(B.size)
print(A.ndim)
print(B.ndim)

(3, 3)
(3, 3)
9
9
2
2


In [25]:
print(A + B)

[[ 3  7 11]
 [15 19 23]
 [27 31 35]]


In [24]:
print(A - B)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [26]:
print(A * B)

[[  2  12  30]
 [ 56  90 132]
 [182 240 306]]


In [27]:
print(np.matmul(A, B))

[[108 132 156]
 [234 294 354]
 [360 456 552]]


In [28]:
print(A.T)
print(B.T)

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


In [29]:
print(np.linalg.det(A))

-7.612957883143941e-15


In [31]:
print(np.linalg.inv(A))

[[ 1.57625987e+15 -3.15251974e+15  1.57625987e+15]
 [-3.15251974e+15  6.30503948e+15 -3.15251974e+15]
 [ 1.57625987e+15 -3.15251974e+15  1.57625987e+15]]


In [32]:
print("Trace of A:", np.trace(A))
print("Trace of B:", np.trace(B))

Trace of A: 30
Trace of B: 27


In [33]:
print("Maximum:", np.max(A))
print("Minimum:", np.min(A))
print("Mean:", np.mean(A))
print("Sum:", np.sum(A))

Maximum: 18
Minimum: 2
Mean: 10.0
Sum: 90


In [35]:
print(np.sum(B, axis=1))

print(np.sum(B, axis=0))

[ 9 27 45]
[21 27 33]


In [36]:
print(A[0])
print(A[:,1])
print(A[-1])
print(A[-1,-1])

[2 4 6]
[ 4 10 16]
[14 16 18]
18


In [37]:
print(A.reshape(1,9))
print(B.flatten())

[[ 2  4  6  8 10 12 14 16 18]]
[ 1  3  5  7  9 11 13 15 17]


In [44]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 3.22336879e+01 -2.23368794e+00 -7.64528572e-16]
Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [43]:
print(np.hstack((A,B)))
print(np.vstack((A,B)))

[[ 2  4  6  1  3  5]
 [ 8 10 12  7  9 11]
 [14 16 18 13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
