In [1]:
import numpy as np

# Student Marks Dataset (out of 100)
marks = np.array([45, 67, 89, 90, 56, 78, 88, 92, 61, 74,
                  83, 95, 52, 68, 71, 85, 77, 64, 58, 81])

print("Dataset:")
print(marks)

Dataset:
[45 67 89 90 56 78 88 92 61 74 83 95 52 68 71 85 77 64 58 81]


In [2]:
print(np.mean(marks))

73.7


In [3]:
print(np.median(marks))

75.5


In [21]:
# 3. Mode
values, counts = np.unique(marks, return_counts=True)
max_count = np.max(counts)

if max_count == 1:
    print("3. Mode: No mode (all values occur once)")
else:
    mode = values[counts == max_count]
    print("3. Mode:", mode)

3. Mode: No mode (all values occur once)


In [5]:
print(np.max(marks))
print(np.min(marks))

95
45


In [6]:
print(np.max(marks) - np.min(marks))

50


In [7]:
print(np.var(marks))

199.21


In [8]:
print(np.std(marks))

14.114177269681715


In [10]:
print(np.percentile(marks,25))

63.25


In [11]:
print(np.percentile(marks,50))

75.5


In [12]:
print(np.percentile(marks,75))

85.75


In [13]:
Q1 = np.percentile(marks, 25)
Q3 = np.percentile(marks, 75)

print("IQR =", Q3 - Q1)

IQR = 22.5


In [14]:
mean = np.mean(marks)
print(np.sum(marks > mean))

11


In [15]:
print(np.sum(marks < 60))

4


In [16]:
total = np.sum(marks)
average = total / len(marks)

print("Sum =", total)
print("Average =", average)

Sum = 1474
Average = 73.7


In [17]:
#ascending
print(np.sort(marks))

[45 52 56 58 61 64 67 68 71 74 77 78 81 83 85 88 89 90 92 95]


In [18]:
#decending
print(np.sort(marks)[::-1])

[95 92 90 89 88 85 83 81 78 77 74 71 68 67 64 61 58 56 52 45]


In [19]:
#top five highest scores
print(np.sort(marks)[-5:][::-1])

[95 92 90 89 88]
